config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :inmuebles
  root "inmuebles#index"
  # get "/inmuebles", to: "inmuebles#index"
  # get 'inmuebles/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inmueble.rb
class Inmueble < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :inmuebles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inmuebles_controller.rb
class InmueblesController < ApplicationController
  before_action :set_inmueble, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /inmuebles or /inmuebles.json
  def index
    @inmuebles = Inmueble.all
  end

  # GET /inmuebles/1 or /inmuebles/1.json
  def show
  end

  # GET /inmuebles/new
  def new
    #@inmueble = Inmueble.new
    @inmueble = current_user.inmuebles.build
  end

  # GET /inmuebles/1/edit
  def edit
  end

  # POST /inmuebles or /inmuebles.json
  def create
    #@inmueble = Inmueble.new(inmueble_params)
    @inmueble = current_user.inmuebles.build(inmueble_params)
    respond_to do |format|
      if @inmueble.save
        format.html { redirect_to inmueble_url(@inmueble), notice: "Inmueble was successfully created." }
        format.json { render :show, status: :created, location: @inmueble }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inmueble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inmuebles/1 or /inmuebles/1.json
  def update
    respond_to do |format|
      if @inmueble.update(inmueble_params)
        format.html { redirect_to inmueble_url(@inmueble), notice: "Inmueble was successfully updated." }
        format.json { render :show, status: :ok, location: @inmueble }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inmueble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inmuebles/1 or /inmuebles/1.json
  def destroy
    @inmueble.destroy

    respond_to do |format|
      format.html { redirect_to inmuebles_url, notice: "Inmueble was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @inmueble = current_user.inmuebles.find_by(id: params[:id])
    redirect_to inmuebles_path, notice: "Not authorized" if @inmueble.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inmueble
      @inmueble = Inmueble.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inmueble_params
      params.require(:inmueble).permit(:address, :price, :rooms, :bathrooms, :area, :description, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inmuebles_helper.rb
module InmueblesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/inmuebles/_form.html.erb
<%= form_with(model: inmueble) do |form| %>
  <% if inmueble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inmueble.errors.count, "error") %> prohibited this inmueble from being saved:</h2>

      <ul>
        <% inmueble.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




  <div class="field form-group">
    <%= form.text_field :address, class:"form-control", placeholder: "Address" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.text_field :price, class:"form-control", placeholder: "Price" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.number_field :rooms, class:"form-control", placeholder: "Rooms" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.number_field :bathrooms, class:"form-control", placeholder: "Bahtrooms" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.text_field :area, class:"form-control", placeholder: "Area" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.text_field :description, class:"form-control", placeholder: "Description" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.number_field :user_id, id: :inmueble_user_id, value: current_user.id, type: "hidden" %>
  </div>
<br>
  <div class="actions">
    <%= form.submit class: "btn btn-dark", value: "Crear Anuncio" %>
  </div>

<% end %>

app/views/inmuebles/edit.html.erb
<h1>Editing Inmueble</h1>
<br>
<%= render 'form', inmueble: @inmueble %>
<br>
<%# link_to 'Show', @inmueble %> |
<%# link_to 'Back', inmuebles_path %>

app/views/inmuebles/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th>Area</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="table-group-divider">
    <% @inmuebles.each do |inmueble| %>
      <tr>
        <td><%= inmueble.address %></td>
        <td><%= inmueble.price %></td>
        <td><%= inmueble.rooms %></td>
        <td><%= inmueble.bathrooms %></td>
        <td><%= inmueble.area %></td>
        <td><%= inmueble.description %></td>
        <td><%= link_to 'Show', inmueble %></td>
        <td><%= link_to 'Edit', edit_inmueble_path(inmueble) %></td>
        <td><%= link_to 'Destroy', inmueble, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inmueble', new_inmueble_path, class:"btn btn-secondary"  %>

app/views/inmuebles/new.html.erb
<h1>Crear Anuncio</h1>
<br>
<%= render 'form', inmueble: @inmueble %>
<br>
<%# link_to 'Back', inmuebles_path, class:"btn btn-dark" %>

app/views/inmuebles/show.html.erb
  <div class="p-5 mb-4 bg-body-tertiary rounded-3">
    <div class="container-fluid py-5">
      <h2 class="display-7 fw-bold"><%= @inmueble.price %> €</h2>
      <hr>
      <h3 class="display-7 fw-bold"><i class="bi bi-geo-alt"></i> <%= @inmueble.address %> </h2>
      <p class="col-md-8 fs-4">  <%= @inmueble.description %></p>
    </div>
    <hr>
    <h2 class="display-7 fw-bold">Características</h2>
      <i class="bi bi-house-add" style="font-size: 2em;"><%= @inmueble.rooms %></i>
      <br>
      <i class="bi bi-droplet" style="font-size: 2em;"><%= @inmueble.bathrooms %></i>
      <br>
      <i class="bi bi-0-square" style="font-size: 2em;"><%= @inmueble.area %></i>
      <br>
      <br>
      <br>
      <button class="btn btn-primary btn-dark" type="button">Contactar</button>
  </div>

<%= link_to 'Edit', edit_inmueble_path(@inmueble), class:"btn btn-secondary" %> 
<%= link_to 'Back', inmuebles_path, class:"btn btn-dark" %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inmoportal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%# javascript_include_tag 'application' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  </head>

  <body>
    <%= render "welcome/navbar" %>
    <div class="container">
    <br/>
      <% if notice %>
        <%= render "layouts/alerts"%>
      <%end%>
      
      <%= yield %>
    </div>
    <script src="/assets/rails-ujs.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js" integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i" crossorigin="anonymous"></script>
  </body>
</html>

app/views/welcome/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand">
        <i class="bi bi-house"></i>
            <%= link_to "Inmoportal", root_path, class:"navbar-brand" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Comprar", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Alquilar", root_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Crear anuncio", new_inmueble_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>

      <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit profile", edit_user_registration_path, class:"nav-link" %>
        </li>

      <% else %>   
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
        </li>
   <% end %>

    </ul>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
Welcome!